import React from 'react';
import { AlertTriangle } from 'lucide-react';

export default function AIDisclaimer() {
  return (
    <div className="mt-6 flex items-start gap-3 p-4 rounded-xl bg-amber-50 border border-amber-100 text-amber-800 shadow-sm">
      <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
      <p className="text-sm leading-relaxed">
        <strong>AI-Assisted Analysis:</strong> The information provided above is generated by artificial intelligence for informational purposes only. It is <span className="underline decoration-amber-300 decoration-2 underline-offset-2">not</span> a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider regarding any medical conditions or questions.
      </p>
    </div>
  );
}
